- name: Check if Swarm has already been initialised
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialise Docker Swarm
  shell: docker swarm init --advertise-addr {{ hostvars['master1']['ansible_eth1'].ipv4.address }}
  when: swarm_status.rc != 0
  run_once: true

#- name: Get the manager join-token
  #shell: docker swarm join-token -q manager
  #register: manager_token

- name: Get the worker join-token
  shell: docker swarm join-token -q worker
  register: worker_token
