- name: install docker & docker-compose
  hosts: all
  become: true
  strategy: free
  roles:
    - base

- name: initialise swarm
  hosts: master1
  become: true
  roles:
    - swarm-init

- name: join swarm
  hosts: worker1, worker2
  become: true
  roles:
    - node-join

#- name: join swarm 2
#  hosts: node2
#  become: true
#  roles:
#    - worker-join



